/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as greeterSol from "./Greeter.sol";
export type { greeterSol };
export type { ClassToken } from "./ClassToken";
